#!/usr/bin/python

# sum of fib <= 4e6, sum of even-valued terms
# they say: Each new term in the Fibonacci sequence is 
# generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# implying F(0) = 1, F(1) = 2
#

last = 1
prev = 1
count = 0
sum = 0
while last <= 4e6:
    if (last%2 == 0):
        print (count,last)
        sum += last
    # end if
    t = prev
    prev = last
    last = t+prev
    count+=1;
# end while

print("sum is: "+str(sum))
